# code/model/persona_academic.py
import json
import logging
import re
from typing import Tuple, Dict, Any, List, Optional

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

import conf
from model.conversation_state import ConversationState
from model.persona_practical import _classify_link, _parse_link_entries
from utils.llm_call import llm_invoke, extract_llm_text
from utils.prompts_academic import SYSTEM_PROMPT as SYSTEM_PROMPT_ACADEMIC

_LOG = logging.getLogger("restbiz.academic")

# Metadata fields with no semantic value for the LLM — always hidden from docs_json
_LLM_HIDDEN_METADATA_KEYS = frozenset({"row_id", "source"})


class AcademicPersonaService:
    """
    Academic Persona (REQUIRED FLOW)
    2.1 Retrieve -> ask REQUIRED SLOTS (dynamic, generated from question + docs)
    2.2 After slots -> ask which SECTIONS (dynamic; only what exists for this case)
    3) Final answer (evidence-only; best-effort)
    4) Mark done for supervisor auto-return

    Production fixes (P0/P1):
    -  Do NOT create academic_flow.stage="idle" automatically
    -  Retrieve ONLY once when starting intake (store academic_question); never re-retrieve on slot replies
    -  Use academic_question for final prompt (never fallback to "1,2" etc.)
    -  Make force_intake meaningful: keep intake stage, re-ask slots on greeting/noise, never reset stage
    -  Stronger greeting/noise detection inside intake (backup safety)
    -  Fix Thai-text false-noise bug (P0): Thai-only responses must NOT be treated as noise
    -  Slots are NOT a numbered menu (P0): do not bind numbers for slot stage
    -  If no sections exist -> answer immediately (P0): do not stall awaiting_sections
    -  NEW: Dynamic slots generated by LLM from user question + docs (not hardcoded template)
    -  NEW: Cross-persona slot memory — skip already-known slots from Practical mode
    -  NEW: Auto-return stores topic context for supervisor to build related topics menu
    -  NEW: LLM call timeout via conf.LLM_REQUEST_TIMEOUT
    """

    persona_id = "academic"

    # For parsing numbered options (used ONLY for section menu, not slots)
    _OPTION_LINE_RE = re.compile(r"(?m)^\s*(\d{1,2})\s*[\)\.\:]\s*(.+?)\s*$")

    # Detect "ทั้งหมด"
    _SELECT_ALL_RE = re.compile(r"(ทั้งหมด|ทุกข้อ|ทุกหัวข้อ|เอาทั้งหมด|all|everything)", re.IGNORECASE)

    # Backup greeting/noise detection (supervisor should already do, but keep safe)
    _TH_LAUGH_RE = re.compile(r"^\s*5{3,}\s*$")
    _EN_GREETING_RE = re.compile(r"^\s*(hi+|hello+|hey+|yo+)\b", re.IGNORECASE)
    _EN_GOOD_TIME_RE = re.compile(r"^\s*good\s+(morning|afternoon|evening|night)\b", re.IGNORECASE)
    _TH_SAWASDEE_FUZZY_RE = re.compile(r"^\s*สว[^\s]{0,6}ดี", re.IGNORECASE)
    _TH_WATDEE_RE = re.compile(r"^\s*หวัดดี", re.IGNORECASE)
    _FILLER_ONLY_RE = re.compile(r"^\s*(ครับ|คับ|ค่ะ|คะ|จ้า|จ้ะ|ค่า|งับ)\s*$", re.IGNORECASE)

    # IMPORTANT P0:
    # Do NOT treat Thai-only text as noise.
    # Only treat as noise when:
    # - very short AND only punctuation/symbols, OR
    # - single repeated character patterns, OR
    # - meaningless latin-only fragments (very short)
    _PUNCT_ONLY_RE = re.compile(r"^\s*[!?.…。，、\-_=+*/\\|@#$%^&*(){}\[\]<>\"'`~:;]+?\s*$")
    _REPEATED_CHAR_RE = re.compile(r"^\s*(.)\1{6,}\s*$")  # e.g., "aaaaaaa", "!!!!!!", "รรรรรรร"
    _LATIN_GIBBERISH_RE = re.compile(r"^\s*[a-z]{1,8}\s*$", re.IGNORECASE)  # tiny latin-only token

    def __init__(self, retriever):
        self.retriever = retriever
        self._init_llm()

    def _init_llm(self):
        model_name = getattr(conf, "OPENROUTER_MODEL_ACADEMIC", conf.OPENROUTER_MODEL)
        timeout = int(getattr(conf, "LLM_REQUEST_TIMEOUT", 30))
        self.llm = ChatOpenAI(
            model=model_name,
            openai_api_key=conf.OPENROUTER_API_KEY,
            openai_api_base=conf.OPENROUTER_BASE_URL,
            temperature=getattr(conf, "TEMPERATURE_ACADEMIC", 0.3),
            max_tokens=getattr(conf, "MAX_TOKENS_ACADEMIC", 10000),
            request_timeout=timeout,
            model_kwargs={"response_format": {"type": "json_object"}},
        )
        # Separate LLM for slot generation.
        # GPT-5.1 is a thinking model — reasoning tokens eat into the budget first.
        # MAX_TOKENS_ACADEMIC_SLOTS (default 3000) gives room for reasoning + actual JSON output.
        slots_max_tokens = getattr(conf, "MAX_TOKENS_ACADEMIC_SLOTS", 3000)
        self.llm_slots = ChatOpenAI(
            model=model_name,
            openai_api_key=conf.OPENROUTER_API_KEY,
            openai_api_base=conf.OPENROUTER_BASE_URL,
            temperature=0.1,
            max_tokens=slots_max_tokens,
            request_timeout=timeout,
            model_kwargs={"response_format": {"type": "json_object"}},
        )

    # Safe append (dedupe) - prefer state helpers when available
    def _append_user_once(self, state: ConversationState, content: str) -> None:
        if hasattr(state, "add_user_message_once"):
            state.add_user_message_once(content)
            return
        if content is None:
            return
        c = str(content)
        if not c.strip():
            return
        if state.messages and state.messages[-1].get("role") == "user" and (state.messages[-1].get("content") or "") == c:
            return
        state.messages.append({"role": "user", "content": c})

    def _append_assistant(self, state: ConversationState, content: str) -> None:
        if hasattr(state, "add_assistant_message_once"):
            state.add_assistant_message_once(content)
            return
        if content is None:
            return
        c = str(content).strip()
        if not c:
            return
        state.messages = state.messages or []
        if state.messages:
            last = state.messages[-1]
            if last.get("role") == "assistant" and (last.get("content") or "").strip() == c:
                return
        state.messages.append({"role": "assistant", "content": c})

    # Context helpers (flow)
    def _get_flow(self, state: ConversationState) -> Optional[Dict[str, Any]]:
        """
        IMPORTANT (P0):
        - Do NOT create flow on read.
        - Return None if flow not started yet.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if isinstance(flow, dict) and str(flow.get("stage") or "").strip():
            return flow
        return None

    def _ensure_flow(self, state: ConversationState, stage: str, **kwargs) -> Dict[str, Any]:
        """
        Create/overwrite flow only when we truly start intake or update a known stage.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if not isinstance(flow, dict):
            flow = {}
        flow["stage"] = stage
        flow.update(kwargs)
        state.context["academic_flow"] = flow
        return flow

    def _set_flow(self, state: ConversationState, **kwargs) -> None:
        """
        Update flow if it exists; create only if 'stage' provided.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if not isinstance(flow, dict):
            flow = {}
        if "stage" in kwargs and kwargs.get("stage"):
            flow["stage"] = kwargs.get("stage")
        for k, v in kwargs.items():
            if k == "stage":
                continue
            flow[k] = v
        if str(flow.get("stage") or "").strip():
            state.context["academic_flow"] = flow

    def _mark_done(self, state: ConversationState) -> None:
        self._set_flow(state, stage="done")
        state.context["auto_return_to_practical"] = True
        # Store topic context so supervisor can build a related-topics menu on auto-return
        topic_ctx = (state.context or {}).get("academic_question", "")
        if topic_ctx:
            state.context["auto_return_topic_context"] = topic_ctx

    # Greeting/noise (backup safety)
    def _looks_like_greeting_or_noise(self, user_text: str) -> bool:
        raw = (user_text or "").strip()
        if not raw:
            return True
        if self._TH_LAUGH_RE.match(raw):
            return True
        if self._FILLER_ONLY_RE.match(raw):
            return True

        low = raw.lower().strip()
        if self._EN_GREETING_RE.match(low) or self._EN_GOOD_TIME_RE.match(low):
            return True
        if self._TH_WATDEE_RE.match(raw) or self._TH_SAWASDEE_FUZZY_RE.match(raw):
            return True

        # P0: do NOT treat Thai-only as noise. Only detect truly noisy patterns.
        if len(raw) <= 16:
            if self._PUNCT_ONLY_RE.match(raw):
                return True
            if self._REPEATED_CHAR_RE.match(raw):
                return True
            if self._LATIN_GIBBERISH_RE.match(raw):
                return True

        return False

    # Retrieval (only once per intake)
    def _retrieve_docs(self, query: str, metadata_filter: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]:
        max_docs = int(getattr(conf, "LLM_DOCS_MAX_ACADEMIC", 12) or 12)
        max_chars = int(getattr(conf, "LLM_DOC_CHARS_ACADEMIC", 700) or 700)

        if metadata_filter:
            vectorstore = getattr(self.retriever, "vectorstore", None)
            if vectorstore is not None:
                try:
                    tmp = vectorstore.as_retriever(search_kwargs={"k": max_docs, "filter": metadata_filter})
                    docs = tmp.invoke(query)
                    _LOG.info("[Academic] Filtered retrieval (filter=%s) got %d docs", metadata_filter, len(docs))
                    if not docs:
                        # Filter returned nothing — fall back to unfiltered
                        _LOG.info("[Academic] Filter returned 0 docs — falling back to unfiltered retrieval")
                        docs = self.retriever.invoke(query)
                except Exception as e:
                    _LOG.warning("[Academic] Filtered retrieval failed (%s), falling back to unfiltered", e)
                    docs = self.retriever.invoke(query)
            else:
                docs = self.retriever.invoke(query)
        else:
            docs = self.retriever.invoke(query)

        results: List[Dict[str, Any]] = []
        for d in (docs or [])[:max_docs]:
            results.append(
                {
                    "content": (getattr(d, "page_content", "") or "")[:max_chars],
                    "metadata": getattr(d, "metadata", {}) or {},
                }
            )

        # INFO-level doc visibility log (always visible in production)
        _LOG.info("[Academic] _retrieve_docs query=%r → %d docs returned", query[:60], len(results))
        for i, r in enumerate(results):
            md = r.get("metadata", {}) or {}
            topic = md.get("operation_topic") or md.get("topic") or md.get("filename") or "?"
            etype = md.get("entity_type_normalized") or md.get("entity_type") or ""
            section = md.get("section") or md.get("doc_type") or ""
            snippet = (r.get("content", "") or "")[:80].replace("\n", " ")
            _LOG.info(
                "  [doc %d/%d] topic=%r entity=%r section=%r | %r",
                i + 1, len(results), topic, etype, section, snippet,
            )

        return results

    def _start_intake_with_retrieval(self, state: ConversationState, user_question: str) -> None:
        """
        P0: Retrieve only here (once), store academic_question, set last_retrieval_query.
        FIX: use conf.DEFAULT_RETRIEVAL_FALLBACK_QUERY as single source of truth for fallback.
        Reuse state.current_docs when already populated by supervisor entity-type filter.
        """
        q = (user_question or "").strip()
        if not q:
            q = getattr(conf, "DEFAULT_RETRIEVAL_FALLBACK_QUERY",
                        "กฎหมายร้านอาหาร ใบอนุญาต ภาษี VAT จดทะเบียน สุขาภิบาล ประกันสังคม")

        state.context = state.context or {}

        # Enrich query with entity type if already known (from practical slot memory)
        if hasattr(state, "get_collected_slots"):
            slots = state.get_collected_slots() or {}
            for k, v in slots.items():
                sv = str(v).strip()
                if k == "entity_type" and sv and sv not in q:
                    q = f"{q} {sv}"
                    break

        state.context["academic_question"] = q

        # Decide whether to reuse pre-retrieved docs from supervisor or do a fresh retrieval.
        # Re-retrieve whenever:
        #   1. state.current_docs is empty / too few (< 2 docs)
        #   2. The new academic question is meaningfully different from the query used for
        #      the pre-retrieved docs (topic changed → must fetch relevant docs fresh).
        def _query_changed(new_q: str, state: "ConversationState") -> bool:  # type: ignore[name-defined]
            """Return True when the stored retrieval query doesn't match the new question."""
            if hasattr(state, "get_last_retrieval_query"):
                old_q = (state.get_last_retrieval_query() or "").strip().lower()
            else:
                old_q = (getattr(state, "last_retrieval_query", "") or "").strip().lower()
            nq = new_q.strip().lower()
            if not old_q:
                return True  # nothing stored → must retrieve
            # Use simple keyword-overlap: if < 30 % of significant words overlap → different topic
            old_words = set(w for w in old_q.split() if len(w) > 2)
            new_words = set(w for w in nq.split() if len(w) > 2)
            if not old_words:
                return True
            overlap = len(old_words & new_words) / len(old_words | new_words)
            changed = overlap < 0.30
            if changed:
                _LOG.info(
                    "[Academic] Query changed (overlap=%.0f%%) — will re-retrieve. old=%r new=%r",
                    overlap * 100, old_q[:60], nq[:60],
                )
            return changed

        needs_fresh = len(state.current_docs or []) < 2 or _query_changed(q, state)

        # Force fresh retrieval when collected slots (entity_type, shop_area_type) were
        # not yet applied to the pre-retrieved docs. Supervisor retrieves unfiltered docs at
        # topic-selection time; academic must re-retrieve with proper metadata filters once
        # the user has answered entity_type / shop_area_type / location_type etc.
        if not needs_fresh and hasattr(state, "get_collected_slots"):
            _slots = state.get_collected_slots() or {}
            _filter_slots = {k: v for k, v in _slots.items()
                             if k in ("entity_type", "shop_area_type", "location_type",
                                      "operation_group", "registration_type")}
            if _filter_slots:
                # Check if current_docs already reflect the entity filter.
                # Many shared docs have entity_type_normalized='' (applies to all entity types).
                # Consider stale ONLY when pre-retrieved docs have NO entity-matched docs
                # and we have MORE than 0 entity-specific docs available.
                _docs_entity = {
                    (d.get("metadata") or {}).get("entity_type_normalized", "").strip()
                    for d in (state.current_docs or [])
                }
                _entity_val = _filter_slots.get("entity_type", "")
                # Pre-retrieved docs are stale when: entity_type is known AND
                # none of the docs carry that entity value (all are unfiltered/empty).
                if _entity_val and _entity_val not in _docs_entity:
                    needs_fresh = True
                    _LOG.info(
                        "[Academic] Force fresh retrieve: entity_type=%r not in docs (docs have %s)",
                        _entity_val, _docs_entity,
                    )
                # Force fresh when registration_type is known but not yet reflected in the
                # last retrieval query (Chroma has no clean registration_type filter field,
                # so we enrich the query string — but only if the retrieval hasn't done so yet).
                if not needs_fresh:
                    _reg_val = _filter_slots.get("registration_type", "")
                    if _reg_val:
                        _last_q = ""
                        if hasattr(state, "get_last_retrieval_query"):
                            _last_q = (state.get_last_retrieval_query() or "").lower()
                        else:
                            _last_q = (getattr(state, "last_retrieval_query", "") or "").lower()
                        if _reg_val.lower() not in _last_q:
                            needs_fresh = True
                            _LOG.info(
                                "[Academic] Force fresh retrieve: registration_type=%r not in last query %r",
                                _reg_val, _last_q[:80],
                            )

        if not needs_fresh:
            _LOG.info("[Academic] Reusing %d pre-retrieved docs from supervisor", len(state.current_docs))
        else:
            # Build metadata filter from collected slots:
            # - entity_type → $or filter: entity_type_normalized = collected_value OR ''
            #   (shared docs with entity='' apply to all entity types, must NOT be excluded)
            # - shop_area_type / location_type → enrich query string only
            metadata_filter: Optional[Dict[str, Any]] = None
            _q_enrichments: list = []
            if hasattr(state, "get_collected_slots"):
                slots = state.get_collected_slots() or {}
                _entity_val_for_filter = None
                for k, v in slots.items():
                    sv = str(v).strip()
                    if not sv:
                        continue
                    if k == "entity_type":
                        _entity_val_for_filter = sv
                    elif k in ("shop_area_type", "location_type", "operation_group", "registration_type"):
                        if sv not in q:
                            _q_enrichments.append(sv)
                # Use $or so shared docs (entity_type_normalized='') are always included
                if _entity_val_for_filter:
                    metadata_filter = {
                        "$or": [
                            {"entity_type_normalized": _entity_val_for_filter},
                            {"entity_type_normalized": ""},
                        ]
                    }
            if _q_enrichments:
                q = f"{q} {' '.join(_q_enrichments)}".strip()
                _LOG.info("[Academic] Query enriched with slots: %r", _q_enrichments)

            # Multi-topic retrieval: if the question covers multiple distinct topics,
            # retrieve for each sub-topic separately then merge (de-dup by content hash).
            # This ensures "VAT + เหล้า" gets docs for both, not just whichever topic
            # happens to rank highest in a single embedding query.
            _MULTI_TOPIC_PATTERNS = [
                # (keyword_in_question, sub_query_to_retrieve)
                (["vat", "ภาษีมูลค่าเพิ่ม", "ภพ", "ภาษี"],
                 "การจดทะเบียนภาษีมูลค่าเพิ่ม VAT เงื่อนไข ขั้นตอน เอกสาร"),
                (["เหล้า", "สุรา", "แอลกอฮอล์", "เครื่องดื่มแอลกอฮอล์", "ใบอนุญาตสุรา"],
                 "ใบอนุญาตจำหน่ายสุราแอลกอฮอล์ เงื่อนไข ขั้นตอน เอกสาร"),
                (["บุหรี่", "ยาสูบ"],
                 "ใบอนุญาตจำหน่ายยาสูบบุหรี่ เงื่อนไข ขั้นตอน"),
                (["สุขาภิบาล", "สุขลักษณะ", "อาหาร"],
                 "ใบอนุญาตสุขาภิบาลอาหาร ร้านอาหาร เงื่อนไข"),
                (["ประกันสังคม", "ลูกจ้าง", "พนักงาน"],
                 "การขึ้นทะเบียนประกันสังคม นายจ้าง"),
            ]

            q_lower = q.lower()
            matched_sub_queries = []
            for keywords, sub_q in _MULTI_TOPIC_PATTERNS:
                if any(kw in q_lower for kw in keywords):
                    matched_sub_queries.append(sub_q)

            if len(matched_sub_queries) >= 2:
                # Multi-topic: retrieve for each sub-topic and merge (interleaved so each topic
                # is represented when we later take [:_MAX_DOCS_ACADEMIC]).
                _LOG.info("[Academic] Multi-topic question detected — retrieving for %d sub-queries", len(matched_sub_queries))
                seen_hashes: set = set()
                per_topic: list = []  # list of lists
                for sq in matched_sub_queries:
                    sub_docs = self._retrieve_docs(sq, metadata_filter=metadata_filter)
                    per_topic.append(sub_docs)
                # Interleave: take 1 from each topic in round-robin, then de-dup
                merged: list = []
                max_len = max((len(t) for t in per_topic), default=0)
                for i in range(max_len):
                    for topic_docs in per_topic:
                        if i < len(topic_docs):
                            doc = topic_docs[i]
                            h = hash(doc.get("content", "")[:100])
                            if h not in seen_hashes:
                                seen_hashes.add(h)
                                merged.append(doc)
                # Also add broad-query docs that weren't captured by sub-queries
                broad_docs = self._retrieve_docs(q, metadata_filter=metadata_filter)
                for doc in broad_docs:
                    h = hash(doc.get("content", "")[:100])
                    if h not in seen_hashes:
                        seen_hashes.add(h)
                        merged.append(doc)
                state.current_docs = merged
                _LOG.info("[Academic] Multi-topic interleaved merge → %d total docs", len(merged))
            else:
                state.current_docs = self._retrieve_docs(q, metadata_filter=metadata_filter)

        if hasattr(state, "set_last_retrieval_query"):
            state.set_last_retrieval_query(q, cache_to_context=True)
        else:
            state.last_retrieval_query = q
            state.context["last_retrieval_query"] = q

    # Option parsing / binding (ONLY for section menu)
    def _extract_numbered_options(self, text: str) -> Dict[int, str]:
        options: Dict[int, str] = {}
        for m in self._OPTION_LINE_RE.finditer(text or ""):
            try:
                k = int(m.group(1))
                v = (m.group(2) or "").strip()
                if v:
                    options[k] = v
            except Exception:
                continue
        return options

    def _parse_numbers(self, user_text: str) -> List[int]:
        if not user_text:
            return []
        nums = [int(x) for x in re.findall(r"\d{1,2}", user_text)]
        nums = [n for n in nums if 0 < n < 100]
        seen = set()
        out = []
        for n in nums:
            if n not in seen:
                seen.add(n)
                out.append(n)
        return out

    def _is_select_all(self, user_text: str) -> bool:
        return bool(self._SELECT_ALL_RE.search(user_text or ""))

    def _bind_choice_if_any(self, state: ConversationState, user_text: str) -> Dict[str, Any]:
        """
        Binder for SECTION stage only.
        Uses state.context["pending_options"] generated by _ask_sections().
        Supports: numbered selection, "ทั้งหมด", and text-based section name (LLM fallback).
        """
        ctx = state.context or {}
        pending = ctx.get("pending_options") or {}
        if not isinstance(pending, dict) or not pending:
            return {"bound": False}

        if self._is_select_all(user_text):
            keys = sorted([int(k) for k in pending.keys() if str(k).isdigit()])
            resolved = [f"{k}) {pending.get(k)}" for k in keys]
            ctx["resolved_selection"] = {"type": "all", "selected": keys, "resolved": resolved, "raw": user_text}
            ctx["pending_options"] = {}
            ctx["pending_question"] = ""
            state.context = ctx
            return {"bound": True, "mode": "all", "selected": keys}

        nums = self._parse_numbers(user_text)
        if nums:
            valid = [n for n in nums if n in pending]
            if not valid:
                return {"bound": False, "reason": "numbers_not_in_options"}

            # If any selected option is "ทั้งหมด" → treat as select-all
            if any(str(pending.get(n, "")).strip() == "ทั้งหมด" for n in valid):
                keys = sorted([int(k) for k in pending.keys() if str(k).isdigit()])
                resolved = [f"{k}) {pending.get(k)}" for k in keys if str(pending.get(k, "")).strip() != "ทั้งหมด"]
                ctx["resolved_selection"] = {"type": "all", "selected": keys, "resolved": resolved, "raw": user_text}
                ctx["pending_options"] = {}
                ctx["pending_question"] = ""
                state.context = ctx
                return {"bound": True, "mode": "all", "selected": keys}

            resolved = [f"{n}) {pending[n]}" for n in valid]
            ctx["resolved_selection"] = {"type": "numbers", "selected": valid, "resolved": resolved, "raw": user_text}
            ctx["pending_options"] = {}
            ctx["pending_question"] = ""
            state.context = ctx
            return {"bound": True, "mode": "numbers", "selected": valid}

        # No number found — try LLM text-to-section matching
        # e.g., "ขอเรื่องค่าธรรมเนียม" → maps to "ค่าธรรมเนียม" option
        opts = {k: v for k, v in pending.items() if str(k).isdigit()}
        if not opts:
            return {"bound": False}

        opt_list = [str(v) for v in opts.values()]
        matched_n = self._match_section_by_text_llm(user_text, opt_list, list(opts.keys()))
        if matched_n is not None and matched_n in pending:
            # Check if matched to "ทั้งหมด"
            if str(pending.get(matched_n, "")).strip() == "ทั้งหมด":
                keys = sorted([int(k) for k in pending.keys() if str(k).isdigit()])
                resolved = [f"{k}) {pending.get(k)}" for k in keys if str(pending.get(k, "")).strip() != "ทั้งหมด"]
                ctx["resolved_selection"] = {"type": "all", "selected": keys, "resolved": resolved, "raw": user_text}
                ctx["pending_options"] = {}
                ctx["pending_question"] = ""
                state.context = ctx
                return {"bound": True, "mode": "all", "selected": keys}
            resolved = [f"{matched_n}) {pending[matched_n]}"]
            ctx["resolved_selection"] = {"type": "numbers", "selected": [matched_n], "resolved": resolved, "raw": user_text}
            ctx["pending_options"] = {}
            ctx["pending_question"] = ""
            state.context = ctx
            return {"bound": True, "mode": "numbers", "selected": [matched_n]}

        return {"bound": False}

    def _match_section_by_text_llm(self, user_text: str, option_labels: List[str], option_keys: List) -> Optional[int]:
        """
        Use LLM (llm_slots) to match free-text section request to a numbered option.
        Returns the matched option number (int key from pending_options) or None.
        """
        opts_str = "\n".join([f"{k}) {v}" for k, v in zip(option_keys, option_labels)])
        prompt = (
            "หน้าที่: จับคู่ข้อความกับตัวเลือกที่ใกล้ที่สุด\n"
            f"ข้อความผู้ใช้: {user_text}\n"
            f"ตัวเลือก:\n{opts_str}\n"
            "กติกา:\n"
            "- ถ้าข้อความตรงกับตัวเลือกใด ให้คืนเลขตัวเลือกนั้น\n"
            "- ถ้าไม่ตรงกับใดเลย ให้คืน null\n"
            "- ห้ามเดาสุ่ม\n"
            'ตอบ JSON เท่านั้น: {"choice": 1} หรือ {"choice": null}'
        )
        try:
            resp = llm_invoke(self.llm_slots, [HumanMessage(content=prompt)], logger=_LOG, label="Academic/section_bind")
            text = extract_llm_text(resp).strip()
            if "```" in text:
                text = text.split("```")[1].split("```")[0].strip() if text.count("```") >= 2 else text
            obj = json.loads(text)
            if isinstance(obj, dict):
                val = obj.get("choice")
                if val is not None:
                    return int(val)
        except Exception:
            pass
        return None

    # Stage 2.1: dynamic slots (LLM-generated from question + docs)
    # Fields to include in slot generation prompt (reduces prompt tokens significantly)
    _SLOT_PROMPT_META_KEYS = (
        "topic_name", "short_name", "regulation_name", "target_audience",
        "conditions_applicability", "entity_type", "location_scope",
    )

    # Chroma metadata fields that (a) vary across docs and (b) can be used as direct Chroma filters.
    # Mapped to: (set of semantically-equivalent known_slot keys that mean "already answered").
    _DIVERSITY_FIELD_EQUIV: Dict[str, frozenset] = {
        "entity_type_normalized": frozenset({
            "entity_type", "entity_type_normalized", "business_type",
            "registration_type", "juristic_type",
        }),
        "location": frozenset({"location", "location_scope", "operation_location"}),
        "area_size": frozenset({"area_size", "shop_area_type"}),
        # registration_type is a sub-type of entity (e.g. บริษัทจำกัด ⊂ นิติบุคคล).
        # Knowing entity_type does NOT answer registration_type — they are different levels.
        # Only skip when registration_type itself is already in collected_slots.
        "registration_type": frozenset({"registration_type"}),
        # operation_by_department kept for query-enrichment; excluded from Chroma filter
        # because full values may not match exactly when LLM shortens them.
        "operation_by_department": frozenset({
            "operation_group", "operation_type", "operation_action", "operation_by_department",
        }),
    }

    def _compute_diversity_from_docs(
        self, docs: List[Dict], known_slots: Dict[str, str]
    ) -> Dict[str, List[str]]:
        """
        Scan docs for metadata fields whose values actually VARY across the retrieved documents
        and are NOT already known from collected_slots.
        Returns {field_name: [sorted distinct values]} — only Chroma-filterable fields.
        Empty dict means no questions needed (all dimensions already determined).
        """
        raw: Dict[str, set] = {}
        for d in (docs or []):
            md = d.get("metadata") or {}
            for field in self._DIVERSITY_FIELD_EQUIV:
                v = md.get(field)
                if v and str(v).strip() and str(v).lower() not in ("nan", "none", ""):
                    raw.setdefault(field, set()).add(str(v).strip()[:80])

        known_keys = set(known_slots.keys())
        result: Dict[str, List[str]] = {}
        for field, equiv_set in self._DIVERSITY_FIELD_EQUIV.items():
            vals = raw.get(field)
            if not vals or len(vals) < 2:
                continue  # No variation → no question needed
            if equiv_set & known_keys:
                continue  # Already answered under some key
            result[field] = sorted(vals)

        # Merge registration_type choices into entity_type_normalized when both have diversity.
        # Without this, the LLM creates TWO separate questions:
        #   Q1: entity_type (บุคคลธรรมดา vs นิติบุคคล)
        #   Q2: registration_type (บริษัทจำกัด / ห้างหุ้นส่วนจำกัด / ...)
        # This is wrong because Q2 is conditional on Q1 = นิติบุคคล.
        # If user picks บุคคลธรรมดา, Q2 has no valid answer.
        #
        # Fix: replace broad "นิติบุคคล" label with its sub-types in the combined choices.
        # Result: ONE question — ก)บุคคลธรรมดา ข)บริษัทจำกัด ค)ห้างหุ้นส่วนจำกัด ง)ห้างหุ้นส่วนสามัญ
        if "entity_type_normalized" in result and "registration_type" in result:
            _entity_vals = set(result["entity_type_normalized"])
            _reg_vals = set(result["registration_type"])
            # Drop the broad "นิติบุคคล" label — it's replaced by its specific sub-types.
            # Keep "บุคคลธรรมดา" since it has no sub-types.
            _combined = {v for v in _entity_vals if v != "นิติบุคคล"}
            _combined.update(_reg_vals)
            if len(_combined) >= 2:
                result["entity_type_normalized"] = sorted(_combined)
                del result["registration_type"]
                _LOG.info(
                    "[Academic] Merged registration_type choices into entity_type_normalized: %s",
                    sorted(_combined),
                )

        return result

    def _build_slot_generation_prompt(
        self,
        user_question: str,
        docs: List[Dict],
        known_slots: Dict[str, str],
        diversity_data: Dict[str, List[str]],
    ) -> str:
        """Build LLM prompt for slot generation. diversity_data must be pre-computed via
        _compute_diversity_from_docs — only fields with actual variation in docs."""

        # Format diversity data clearly: field → exact values from Chroma
        diversity_lines = []
        for field, vals in diversity_data.items():
            diversity_lines.append(f'  "{field}": {json.dumps(vals, ensure_ascii=False)}')

        diversity_section = (
            "\nField ที่มีค่าต่างกันใน data (นี่คือ ONLY fields ที่ถามได้):\n"
            + "\n".join(diversity_lines)
            + "\n"
        )

        known_str = json.dumps(known_slots, ensure_ascii=False) if known_slots else "{}"
        valid_keys_str = json.dumps(list(diversity_data.keys()), ensure_ascii=False)

        return f"""หน้าที่: วิเคราะห์คำถามและข้อมูล แล้วสร้างคำถามที่จำเป็นเพื่อให้ตอบได้ตรงกรณีของผู้ใช้

คำถามผู้ใช้: {user_question}

ข้อมูลที่รู้แล้ว (ห้ามถามซ้ำ): {known_str}
{diversity_section}
กติกาเคร่งครัด (ห้ามฝ่าฝืน):
1. `key` ต้องเป็นชื่อ field จาก list นี้เท่านั้น: {valid_keys_str}
   ห้ามใช้ key อื่นที่ไม่อยู่ใน list — ถ้า key ไม่อยู่ใน list ระบบจะทิ้งคำถามนั้นทิ้งทั้งหมด
2. `choices` ต้องเป็น values จาก field นั้นในรายการ "Field ที่มีค่าต่างกัน" ด้านบนเท่านั้น
   ห้ามสร้าง choice ใหม่ที่ไม่มีใน data — คัดลอกค่าตรงๆ จากรายการด้านบน
3. ถามเฉพาะ field ที่ถ้า user ตอบต่างกัน → จะดึงเอกสารต่างชุดกันจาก database
   ถ้า user ตอบอย่างไรก็ได้คำตอบเดิม → ห้ามถาม
4. ห้ามถาม "หัวข้อ/ส่วนที่อยากรู้" เช่น ขั้นตอน/เอกสาร/ค่าธรรมเนียม/ระยะเวลา
5. ถามได้สูงสุด 4 ข้อ เรียงจาก field ที่แยก case ได้มากที่สุดก่อน
6. กฎรวม sub-types: ถ้า entity_type_normalized มีทั้ง "บุคคลธรรมดา" และ registration sub-types
   ให้รวม sub-types ทั้งหมดเป็น choices เดียวโดยตรง ห้ามถามสองชั้น
7. ถ้าคำถาม user เฉพาะเจาะจงพอแล้ว หรือ fields ทั้งหมดอยู่ใน known_slots แล้ว → return slots: []

ตอบ JSON เท่านั้น:
{{"slots": [{{"key": "entity_type_normalized", "question": "ร้านของคุณเปิดในนามอะไรครับ?", "choices": ["บุคคลธรรมดา", "บริษัทจำกัด", "ห้างหุ้นส่วนจำกัด"]}}]}}"""

    def _parse_slots_llm_response(self, raw: str) -> List[Dict]:
        """Parse LLM JSON response into list of slot dicts. Returns [] on failure."""
        text = (raw or "").strip()
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0].strip()
        elif "```" in text:
            text = text.split("```")[1].split("```")[0].strip()
        try:
            result = json.loads(text)
            if isinstance(result, dict):
                return result.get("slots") or []
        except Exception:
            pass
        return []

    _CHOICE_LABELS = ("ก", "ข", "ค", "ง")

    def _render_slot_message(self, needed: List[Dict], state: Optional["ConversationState"] = None) -> str:
        """Build the slot question message. Stores per-slot and global choice maps in state."""
        lines = ["เพื่อตอบได้ตรงกรณีของคุณ รบกวนตอบรวดเดียวครับ (ตอบเท่าที่รู้)"]
        choice_map: Dict[str, str] = {}          # global fallback label → text
        slot_choice_maps: Dict[str, Dict[str, str]] = {}  # slot_key → {label → text}
        for i, slot in enumerate(needed, 1):
            q_text = (slot.get("question") or "").strip()
            if not q_text:
                continue
            key = slot.get("key") or f"slot_{i}"
            choices = slot.get("choices") or []
            lines.append(f"{i}) {q_text}")
            per_slot: Dict[str, str] = {}
            for j, c in enumerate(choices[:4]):
                lbl = self._CHOICE_LABELS[j]
                lines.append(f"   {lbl}) {c}")
                per_slot[lbl] = c
                per_slot[lbl.lower()] = c
                # global map: last-write wins (used only for single-question fallback)
                choice_map[lbl] = c
                choice_map[lbl.lower()] = c
            slot_choice_maps[key] = per_slot
        if state is not None:
            ctx = state.context or {}
            if slot_choice_maps:
                ctx["dynamic_slot_choice_maps"] = slot_choice_maps  # per-slot (authoritative)
            if choice_map:
                ctx["dynamic_slot_choice_map"] = choice_map          # global (backward compat)
            state.context = ctx
        return "\n".join(lines)

    def _generate_dynamic_slots(self, state: ConversationState) -> str:
        """
        Generate slot questions dynamically using LLM based on:
        - user's actual question
        - retrieved documents (lean metadata only)
        - already-known slots (from cross-persona memory)

        Strategy A (primary): lean prompt → GPT-5.1 with MAX_TOKENS_ACADEMIC_SLOTS
        Strategy B (retry fallback): minimal prompt, same diversity constraints
        Returns empty string when no questions needed (all slots known / no variation in data).
        """
        ctx = state.context or {}
        user_q = ctx.get("academic_question", "")
        known_slots = state.get_collected_slots() if hasattr(state, "get_collected_slots") else {}

        # Pre-compute which fields actually vary in the docs and are not yet known.
        # Fast path: if nothing varies → no questions to ask, go straight to sections.
        diversity_data = self._compute_diversity_from_docs(state.current_docs or [], known_slots)
        if not diversity_data:
            _LOG.info("[Academic] No varying data fields beyond known slots — skipping slot questions")
            return ""

        # ── Strategy A: lean prompt constrained to diversity fields ──
        prompt_a = self._build_slot_generation_prompt(user_q, state.current_docs or [], known_slots, diversity_data)
        slots_data: List[Dict] = []
        try:
            resp = llm_invoke(self.llm_slots, [HumanMessage(content=prompt_a)], logger=_LOG, label="Academic/slots", state=state)
            slots_data = self._parse_slots_llm_response(extract_llm_text(resp))
        except Exception as e:
            _LOG.warning("[Academic] Slot generation (A) failed: %s — retrying with lean prompt", e)

        # ── Strategy B: minimal fallback — also constrained to diversity fields ──
        if not slots_data:
            known_str = json.dumps(known_slots, ensure_ascii=False) if known_slots else "{}"
            diversity_str = "\n".join(
                f'  "{field}": {json.dumps(vals, ensure_ascii=False)}'
                for field, vals in diversity_data.items()
            )
            valid_keys_str = json.dumps(list(diversity_data.keys()), ensure_ascii=False)
            prompt_b = (
                f"หน้าที่: สร้างคำถามที่จำเป็นเพื่อให้ตอบคำถามนี้ได้ตรงกรณี\n"
                f"คำถามผู้ใช้: {user_q}\n"
                f"ข้อมูลที่รู้แล้ว (ห้ามถามซ้ำ): {known_str}\n\n"
                f"Fields ที่มีค่าต่างกันใน data (ถามได้เฉพาะ fields เหล่านี้):\n{diversity_str}\n\n"
                f"กติกาเคร่งครัด:\n"
                f"- `key` ต้องเป็น field จาก list นี้เท่านั้น: {valid_keys_str}\n"
                f"- `choices` ต้องเป็น values จากรายการด้านบนเท่านั้น — คัดลอกค่าตรงๆ\n"
                f"- ถามเฉพาะที่ทำให้ตอบต่างกันจริงๆ สูงสุด 4 ข้อ\n"
                f"- ห้ามถามว่าอยากรู้เรื่องอะไร (ขั้นตอน/เอกสาร/ค่าธรรมเนียม)\n"
                f"- ถ้าไม่จำเป็น return {{\"slots\": []}}\n"
                f"ตอบ JSON: {{\"slots\": [...]}}"
            )
            try:
                resp_b = llm_invoke(self.llm_slots, [HumanMessage(content=prompt_b)], logger=_LOG, label="Academic/slots_retry", state=state)
                slots_data = self._parse_slots_llm_response(extract_llm_text(resp_b))
            except Exception as e2:
                _LOG.warning("[Academic] Slot generation (B) also failed: %s", e2)

        # Filter out already-known slot keys (exact match)
        needed = [s for s in slots_data
                  if isinstance(s, dict) and s.get("key") and s["key"] not in known_slots]

        # Semantic dedup: if known_slots already has registration/entity type info,
        # drop any LLM-generated slot that is semantically equivalent (LLM may use different key names)
        _ENTITY_REG_KEYS = {
            "registration_type", "entity_type", "entity_type_normalized",
            "business_type", "juristic_type", "company_type", "org_type", "organization_type",
        }
        _known_has_reg = bool(known_slots.keys() & _ENTITY_REG_KEYS)
        if _known_has_reg:
            needed = [s for s in needed if s.get("key") not in _ENTITY_REG_KEYS]

        # Semantic dedup: if known_slots already has location/area info,
        # drop any LLM-generated slot with a different key name for the same concept
        _LOCATION_KEYS = {
            "location", "area_size", "location_scope", "shop_area_type",
            "operation_location", "province", "region",
        }
        _known_has_location = bool(known_slots.keys() & _LOCATION_KEYS)
        if _known_has_location:
            needed = [s for s in needed if s.get("key") not in _LOCATION_KEYS]

        # Semantic dedup: if known_slots already has operation group/type info,
        # drop any LLM-generated slot asking the same thing under a different key name
        _OPERATION_GROUP_KEYS = {
            "operation_group", "operation_type", "operation_action",
            "operation_by_department", "action_type", "operation_mode",
        }
        _known_has_op_group = bool(known_slots.keys() & _OPERATION_GROUP_KEYS)
        if _known_has_op_group:
            needed = [s for s in needed if s.get("key") not in _OPERATION_GROUP_KEYS]

        # Post-validate: only keep slots whose key is in diversity_data.
        # Prevents hallucinated keys (e.g. "shop_type", "employee_count") from reaching users.
        _valid_diversity_keys = set(diversity_data.keys())
        needed = [s for s in needed if s.get("key") in _valid_diversity_keys]
        _LOG.info("[Academic] After key validation: %d slots remain (valid keys: %s)",
                  len(needed), list(_valid_diversity_keys))

        # Hard cap: max 4 slots regardless of LLM output
        needed = needed[:4]

        if not needed:
            # LLM confirmed no slots needed (question specific enough) OR both attempts failed
            if not slots_data:
                # Both LLM calls failed entirely — log warning but do NOT silently skip
                _LOG.error("[Academic] Both slot generation attempts failed — proceeding to section menu")
            else:
                _LOG.info("[Academic] No slots needed (all known or question is specific)")
            return ""

        # Build message (pass state so choice_map gets stored for label resolution)
        msg = self._render_slot_message(needed, state=state)

        # Store slot keys for later context enrichment
        state.context["dynamic_slot_keys"] = [s.get("key") for s in needed if s.get("key")]
        state.context["pending_options"] = {}
        state.context["pending_question"] = ""
        self._set_flow(state, stage="awaiting_slots")
        return msg

    def _ask_required_slots(self, state: ConversationState) -> str:
        """
        Entry point for slot phase — tries dynamic generation first,
        falls back to topic-aware defaults if LLM unavailable.
        P0: Slots are NOT a selection menu. Do NOT set pending_options here.
        """
        msg = self._generate_dynamic_slots(state)
        if msg:
            return msg
        # Empty string means all slots already known — signal caller to skip to sections
        return ""

    def _save_slots_best_effort(self, state: ConversationState, user_text: str) -> None:
        ctx = state.context or {}
        slots = ctx.get("academic_slots")
        if not isinstance(slots, dict):
            slots = {}

        raw = (user_text or "").strip()
        choice_map = ctx.get("dynamic_slot_choice_map") or {}
        slot_choice_maps = ctx.get("dynamic_slot_choice_maps") or {}  # per-slot (authoritative)
        slot_keys = ctx.get("dynamic_slot_keys") or []

        # Parse multi-answer responses like "ก ค ก" or "1 3 2" into per-slot values using per-slot maps.
        # Labels repeat across questions (each question has its own ก/ข/ค/ง), so we must use
        # the per-slot map for the i-th answer → i-th slot key.
        # Also support numeric answers "1"/"2"/"3"/"4" → mapped to ก/ข/ค/ง index.
        if slot_keys and slot_choice_maps:
            tokens = re.split(r"[\s,/]+", raw)
            _valid_labels = set(self._CHOICE_LABELS) | {l.lower() for l in self._CHOICE_LABELS}
            _num_to_label = {"1": "ก", "2": "ข", "3": "ค", "4": "ง"}
            # Normalise each token: numeric → Thai label; keep existing Thai labels; drop rest
            labels = []
            for t in tokens:
                t = t.strip()
                if t in _valid_labels:
                    labels.append(t)
                elif t in _num_to_label:
                    labels.append(_num_to_label[t])
            for i, key in enumerate(slot_keys):
                if i >= len(labels):
                    break
                label = labels[i]
                per_map = slot_choice_maps.get(key, {})
                val = per_map.get(label) or per_map.get(label.lower()) or choice_map.get(label) or label
                if val:
                    # Special handling for entity_type_normalized when choices were merged with
                    # registration sub-types (from _compute_diversity_from_docs merge logic).
                    # If the user's answer is a specific sub-type (e.g. บริษัทจำกัด), we must:
                    #   1. Save registration_type = original answer (บริษัทจำกัด)
                    #   2. Normalize entity_type_normalized = "นิติบุคคล" (not บริษัทจำกัด)
                    # Without this, the Chroma filter would look for entity_type_normalized="บริษัทจำกัด"
                    # which doesn't exist — it would find 0 docs.
                    if key == "entity_type_normalized":
                        try:
                            from service.data_loader import DataLoader as _DL
                            _normalized = _DL._normalize_entity_type(val)
                        except Exception:
                            _normalized = None
                        if _normalized and _normalized != val:
                            # val is a registration sub-type — save both registration_type and normalized entity
                            slots["registration_type"] = val
                            slots[key] = _normalized
                            try:
                                state.save_collected_slot("registration_type", val)
                            except Exception as _e:
                                _LOG.warning("[Academic] save_collected_slot failed key='registration_type' val=%r: %s", val, _e)
                            try:
                                state.save_collected_slot(key, _normalized)
                            except Exception as _e:
                                _LOG.warning("[Academic] save_collected_slot failed key=%r val=%r: %s", key, _normalized, _e)
                            _LOG.info(
                                "[Academic] entity_type_normalized merged-answer: %r → entity=%r reg=%r",
                                val, _normalized, val,
                            )
                            continue
                    slots[key] = val
                    try:
                        state.save_collected_slot(key, val)
                    except Exception as _e:
                        _LOG.warning("[Academic] save_collected_slot failed key=%r val=%r: %s", key, val, _e)

        # Fallback: resolve single-label/numeric input "ก"/"1" → actual text via global map
        resolved_raw = raw
        _num_to_label_fb = {"1": "ก", "2": "ข", "3": "ค", "4": "ง"}
        _lookup_key = _num_to_label_fb.get(raw.strip(), raw.strip())
        if choice_map and _lookup_key in choice_map:
            resolved_raw = choice_map[_lookup_key]
        elif choice_map and raw in choice_map:
            resolved_raw = choice_map[raw]

        slots["raw"] = resolved_raw
        ctx["academic_slots"] = slots
        state.context = ctx

    def _re_retrieve_with_slots(self, state: ConversationState) -> None:
        """
        After academic slot answers are saved, re-retrieve docs from Chroma using those
        slot values as metadata filters. Only applies to Chroma-filterable fields
        (entity_type_normalized, location, area_size, registration_type).
        operation_by_department is used for query enrichment (not direct filter) because
        its stored values are long descriptions that may not match the LLM-shortened choices.

        Falls back to existing docs if filtered retrieval returns 0 results.
        """
        ctx = state.context or {}
        slots = ctx.get("academic_slots") or {}

        # Fields that map cleanly to Chroma metadata keys for exact-match filtering
        _DIRECT_FILTER_FIELDS = frozenset({
            "entity_type_normalized", "location", "area_size", "registration_type",
        })

        filter_parts: List[Dict] = []
        query_enrichments: List[str] = []
        query = (ctx.get("academic_question") or "").strip()

        for key, val in slots.items():
            if key == "raw":
                continue
            sv = (str(val) if val else "").strip()
            if not sv or sv.lower() in ("nan", "none", ""):
                continue

            if key == "entity_type_normalized":
                # Always include universal docs (entity_type_normalized='')
                filter_parts.append({
                    "$or": [
                        {"entity_type_normalized": sv},
                        {"entity_type_normalized": ""},
                    ]
                })
            elif key in _DIRECT_FILTER_FIELDS:
                filter_parts.append({key: sv})
            elif key == "operation_by_department":
                # Query enrichment only — stored values may differ from displayed choice text
                if sv not in query:
                    query_enrichments.append(sv)

        if not filter_parts and not query_enrichments:
            return  # Nothing to filter or enrich

        # Enrich query with operation context
        if query_enrichments:
            query = f"{query} {' '.join(query_enrichments)}".strip()
            _LOG.info("[Academic] slot re-retrieve: query enriched with %r", query_enrichments)

        if not filter_parts:
            if query_enrichments:
                # No direct Chroma filter but we have query enrichments (e.g. operation_by_department).
                # Update academic_question so the LLM prompt reflects the operation context,
                # then do a fresh re-retrieve — the comment "will naturally be included" was wrong:
                # _finalize_answer uses academic_question as-is without re-retrieving.
                state.context["academic_question"] = query
                new_docs_qe = self._retrieve_docs(query)
                if new_docs_qe:
                    state.current_docs = new_docs_qe
                    if hasattr(state, "last_retrieval_query"):
                        state.last_retrieval_query = query
                    _LOG.info(
                        "[Academic] Re-retrieved %d docs with query enrichment (operation_by_department)",
                        len(new_docs_qe),
                    )
                else:
                    _LOG.info(
                        "[Academic] Query enrichment re-retrieve 0 docs — keeping existing, academic_question updated"
                    )
            return

        # Build combined Chroma filter
        chroma_filter: Dict = filter_parts[0] if len(filter_parts) == 1 else {"$and": filter_parts}

        # Re-retrieve using _retrieve_docs (handles fallback + logging)
        new_docs = self._retrieve_docs(query, metadata_filter=chroma_filter)
        if new_docs:
            state.current_docs = new_docs
            # Update stored query so staleness check reflects the new enriched query
            if hasattr(state, "last_retrieval_query"):
                state.last_retrieval_query = query
            _LOG.info(
                "[Academic] Re-retrieved %d docs after slot answers (filter=%r)",
                len(new_docs), chroma_filter,
            )
        else:
            _LOG.info(
                "[Academic] Slot re-retrieval returned 0 docs — keeping existing %d docs",
                len(state.current_docs or []),
            )

    # Stage 2.2: dynamic section menu (only what exists)
    def _available_sections_from_docs(self, state: ConversationState) -> List[Dict[str, str]]:
        docs = state.current_docs or []

        def has_any_metadata(keys: List[str]) -> bool:
            for d in docs:
                md = (d.get("metadata") or {})
                for key in keys:
                    val = md.get(key)
                    if val is None:
                        continue
                    s = str(val).strip()
                    if s and s.lower() != "nan":
                        return True
            return False

        def has_any_content(keywords: List[str]) -> bool:
            # P1: fallback if metadata is missing
            kws = [k for k in (keywords or []) if k]
            if not kws:
                return False
            for d in docs:
                content = (d.get("content") or "")
                for kw in kws:
                    if kw and kw in content:
                        return True
            return False

        candidates = [
            (
                ["operation_steps", "operation_step", "steps", "procedure", "ขั้นตอนการดำเนินการ"],
                "ขั้นตอนการดำเนินการ",
                ["ขั้นตอน", "ยื่น", "ดำเนินการ", "procedure", "steps"],
            ),
            (
                ["identification_documents", "documents", "required_documents", "เอกสาร ยืนยันตัวตน", "เอกสารที่ต้องใช้"],
                "เอกสารที่ต้องใช้",
                ["เอกสาร", "สำเนา", "แบบฟอร์ม", "documents"],
            ),
            (["fees", "fee", "ค่าธรรมเนียม"], "ค่าธรรมเนียม", ["ค่าธรรมเนียม", "fee", "ชำระ"]),
            (["operation_duration", "duration", "ระยะเวลา การดำเนินการ", "ระยะเวลาดำเนินการ"], "ระยะเวลา", ["ระยะเวลา", "วันทำการ", "duration"]),
            (["service_channel", "channel", "ช่องทางการ ให้บริการ", "ช่องทาง", "หน่วยงาน", "department"], "ช่องทาง/สถานที่ยื่น", ["ช่องทาง", "หน่วยงาน", "สำนักงาน", "department"]),
            # ❗ metadata-only: content keywords เป็น false positive สูง — เปิด choice เฉพาะเมื่อมี field ส่งให้ LLM จริงๆ
            (["terms_and_conditions", "conditions", "เงื่อนไขและหลักเกณฑ์"], "เงื่อนไขและหลักเกณฑ์", None),
            (["legal_regulatory", "law", "regulation", "ข้อกำหนดทางกฎหมาย และข้อบังคับ", "บทลงโทษ"], "ข้อกฎหมาย/ข้อควรระวัง/บทลงโทษ", None),
            (["research_reference"], "แบบฟอร์มและเอกสารที่เกี่ยวข้อง", ["แบบ บอจ", "แบบ ภพ", "แบบ ก.", "แบบ ว.", "ดาวน์โหลด", "คู่มือ", "http"]),
        ]

        out: List[Dict[str, str]] = []
        for keys, label, kws in candidates:
            if has_any_metadata(keys):
                out.append({"key": keys[0], "label": label})
            elif kws and has_any_content(kws):  # content fallback only when kws is not None
                out.append({"key": keys[0], "label": label})
        return out

    def _ask_sections(self, state: ConversationState) -> str:
        sections = self._available_sections_from_docs(state)

        if not sections:
            # P0: no sections -> proceed to final immediately (caller will handle)
            state.context["selected_sections"] = {"type": "all", "keys": []}
            state.context["section_catalog"] = []
            state.context["pending_options"] = {}
            state.context["pending_question"] = ""
            self._set_flow(state, stage="no_sections")
            return ""

        lines = ["คุณอยากรู้เรื่องไหนครับ"]
        opts: Dict[int, str] = {}
        for i, sec in enumerate(sections, start=1):
            opts[i] = sec["label"]
            lines.append(f"{i}) {sec['label']}")
        all_n = len(sections) + 1
        opts[all_n] = "ทั้งหมด"
        lines.append(f"{all_n}) ทั้งหมด")

        msg = "\n".join(lines)

        state.context["section_catalog"] = sections
        state.context["pending_options"] = opts
        state.context["pending_question"] = msg
        self._set_flow(state, stage="awaiting_sections")
        return msg

    def _save_selected_sections(self, state: ConversationState, user_text: str, bind_info: Dict[str, Any]) -> None:
        ctx = state.context or {}
        catalog = ctx.get("section_catalog") or []
        if not isinstance(catalog, list):
            catalog = []

        if self._is_select_all(user_text) or (bind_info.get("bound") and bind_info.get("mode") == "all"):
            ctx["selected_sections"] = {"type": "all", "keys": [c.get("key") for c in catalog if c.get("key")]}
            state.context = ctx
            return

        nums = bind_info.get("selected") if bind_info.get("bound") and bind_info.get("mode") == "numbers" else []
        if not nums:
            ctx["selected_sections"] = {"type": "all", "keys": [c.get("key") for c in catalog if c.get("key")]}
            state.context = ctx
            return

        picked: List[str] = []
        for n in nums:
            idx = int(n) - 1
            if 0 <= idx < len(catalog):
                k = catalog[idx].get("key")
                if k:
                    picked.append(k)

        if not picked:
            picked = [c.get("key") for c in catalog if c.get("key")]

        ctx["selected_sections"] = {"type": "picked", "keys": picked}
        state.context = ctx

    # Final answer generation (LLM JSON)
    def _call_llm_json(self, prompt: str, max_retries: int = 2, state: Optional[ConversationState] = None) -> dict:
        last_err = None
        for _ in range(max_retries):
            try:
                resp = llm_invoke(self.llm, [SystemMessage(content=SYSTEM_PROMPT_ACADEMIC), HumanMessage(content=prompt)], logger=_LOG, label="Academic/json", state=state)
                text = extract_llm_text(resp).strip()

                if "```json" in text:
                    text = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()

                obj = json.loads(text)
                return obj if isinstance(obj, dict) else {}
            except Exception as e:
                # 🎯 LengthFinishReasonError: input เดิม → ผลเดิม — break ทันที ไม่เสียเวลา retry
                if "LengthFinishReasonError" in type(e).__name__ or "LengthFinishReason" in str(e)[:80]:
                    _LOG.warning("[Academic/json] LengthFinishReasonError — max_tokens น้อยเกินไป, skip retry")
                    last_err = e
                    break
                last_err = e
                continue

        if last_err:
            _LOG.warning("[Academic] LLM JSON parse failed: %s", last_err)

        return {
            "input_type": "new_question",
            "analysis": "LLM JSON parse failed",
            "action": "answer",
            "execution": {
                "answer": "ขอโทษครับ ตอนนี้ยังสรุปคำตอบที่ยืนยันได้จากเอกสารไม่ได้",
                "context_update": {"auto_return_to_practical": True},
            },
        }

    def _build_final_prompt(self, state: ConversationState, user_question: str) -> str:
        ctx = state.context or {}
        slots = ctx.get("academic_slots") or {}
        selected = ctx.get("selected_sections") or {"type": "all", "keys": []}

        # 🎯 Token: เหลือแค่ 12 docs (academic needs full coverage)
        _MAX_DOCS_ACADEMIC = int(getattr(conf, "LLM_DOCS_MAX_ACADEMIC", 12))
        # 🎯 Whitelist + per-field caps — research_reference/operation_steps are long (~600-2285 chars)
        _ACADEMIC_META_WHITELIST = {
            # Source type — lets LLM know if doc is regulatory/marketing/business_guide
            "data_type",
            # Regulatory fields
            "license_type", "operation_topic",
            "entity_type_normalized", "registration_type", "department",
            "fees", "operation_duration",
            # Section-backing fields: must be whitelisted so LLM can actually answer these sections
            "terms_and_conditions", "conditions",
            "legal_regulatory", "law", "regulation",
            "service_channel", "service_hours", "service_location",
            # Marketing / business_guide fields (data_loader_general.py)
            "main_topic", "sub_topic", "answer_guideline",
        }
        # research_reference is aggregated separately below (deduped) — skip from per-doc metadata
        _ACADEMIC_FIELD_CAPS = {
            "fees": 150, "operation_duration": 150,
            # cap the longer legal/condition fields to avoid token explosion
            "terms_and_conditions": 400, "conditions": 400,
            "legal_regulatory": 600, "law": 400, "regulation": 400,
            "service_channel": 300, "service_hours": 150, "service_location": 150,
            "identification_documents": 1500,  # never truncate doc lists
            # marketing / business_guide content cap
            "answer_guideline": 600, "main_topic": 120, "sub_topic": 150,
        }
        # Long fields: send once (first doc that has them) to avoid ×N repetition
        # identification_documents is intentionally excluded — it varies by entity_type and must
        # come from every matching doc so the complete list reaches the LLM.
        _ACADEMIC_LONG_FIELDS = {"operation_steps"}
        _academic_long_sent = False
        docs_json = []
        for d in (state.current_docs or [])[:_MAX_DOCS_ACADEMIC]:
            md = d.get("metadata", {}) or {}
            filtered_md = {}
            for k, v in md.items():
                if k not in _ACADEMIC_META_WHITELIST and k not in _ACADEMIC_LONG_FIELDS:
                    continue
                if v in (None, "", "nan", "None"):
                    continue
                if k in _ACADEMIC_LONG_FIELDS and _academic_long_sent:
                    continue
                v_str = str(v)
                cap = _ACADEMIC_FIELD_CAPS.get(k)
                filtered_md[k] = v_str[:cap] if cap and len(v_str) > cap else v_str
            if any(k in filtered_md for k in _ACADEMIC_LONG_FIELDS):
                _academic_long_sent = True
            docs_json.append(
                {
                    "metadata": filtered_md,
                    # content already clipped to LLM_DOC_CHARS_ACADEMIC by _retrieve_docs()
                    "content": (d.get("content", "") or ""),
                }
            )

        # Aggregate form_links.
        # For multi-topic questions, include links from ALL retrieved docs (not filtered to single topic).
        # For single-topic questions, still deduplicate by license_type naturally.
        _lt_counts: Dict[str, int] = {}
        for d in (state.current_docs or [])[:_MAX_DOCS_ACADEMIC]:
            lt = ((d.get("metadata") or {}).get("license_type") or "").strip()
            if lt:
                _lt_counts[lt] = _lt_counts.get(lt, 0) + 1
        # _primary_lt used only for display label, not as a filter anymore
        _primary_lt = max(_lt_counts, key=_lt_counts.__getitem__) if _lt_counts else None
        _is_multi_topic = len(_lt_counts) >= 2

        # Parse research_reference into (desc, url) pairs — deduplicated across docs.
        # Using shared _parse_link_entries from persona_practical (same format).
        _seen_ref_keys: set = set()
        _link_entries: list = []            # (desc, url) pairs, deduplicated
        for _d in (state.current_docs or [])[:_MAX_DOCS_ACADEMIC]:
            _md = _d.get("metadata") or {}
            _rr = (_md.get("research_reference") or "").strip()
            for _rd, _ru in _parse_link_entries(_rr):
                _rkey = _ru or _rd
                if _rkey and _rkey not in _seen_ref_keys:
                    _seen_ref_keys.add(_rkey)
                    _link_entries.append((_rd, _ru))

        # NEW POLICY: Only inject links when user explicitly selected sections (not default/auto)
        # Links are shown ONLY when:
        # - User completed section selection (not auto-finalized), AND
        # - Selected "research_reference" section (แบบฟอร์มและเอกสาร) OR "all"/"picked-all" (ทั้งหมด)
        # NOTE: type ที่เป็นไปได้: "all", "picked", "specific" — ต้องรวม "picked" ด้วย
        _user_selected_sections = selected.get("type") in ("all", "picked", "specific")
        _ref_section_requested = (
            _user_selected_sections
            and (
                selected.get("type") == "all"
                or "research_reference" in (selected.get("keys") or [])
            )
        )

        # ตรวจว่า user ถาม "อ้างอิง" โดยตรงหรือเปล่า (เพื่อ unlock reference links)
        _user_asked_reference = bool(re.search(
            r"(อ้างอิง|reference|research|เอกสารอ้างอิง|แหล่งอ้างอิง|กฎหมายอ้างอิง)",
            user_question, re.IGNORECASE
        ))

        # ── 4-category link classification using shared _classify_link ──────────────
        # Type 4: registration  → always shown (service portals)
        # Type 1: form/document → shown in both bots when section is selected
        # Type 2: guide/tutorial→ academic only, max 1 most important link
        # Type 3: ref/FAQ/law   → only when user explicitly asks for อ้างอิง
        _service_entries: list = []
        _form_entries:    list = []
        _guide_entries:   list = []
        _ref_entries:     list = []

        for _rd, _ru in _link_entries:
            _cat = _classify_link(_rd, _ru)
            if _cat == "registration":
                _service_entries.append((_rd, _ru))
            elif _cat == "form":
                _form_entries.append((_rd, _ru))
            elif _cat == "guide":
                _guide_entries.append((_rd, _ru))
            else:
                _ref_entries.append((_rd, _ru))

        if _is_multi_topic:
            _instruction = f" (หลาย topics: {', '.join(_lt_counts.keys())})"
        elif _primary_lt:
            _instruction = f" (topic: '{_primary_lt}')"
        else:
            _instruction = ""

        def _fmt_link(desc: str, url: str) -> str:
            if desc and url:
                return f"- {desc}\n  {url}"
            return f"- {url or desc}"

        # SERVICE_LINKS → always injected, no section condition
        _service_section = ""
        if _service_entries:
            _service_section = (
                f"\n🌐 SERVICE_LINKS{_instruction} — copy เหล่านี้ into section '🌐 ช่องทางยื่นออนไลน์' ทุก answer (แสดง URL ตรงๆ ห้าม paraphrase):\n"
                + "\n".join(_fmt_link(d, u) for d, u in _service_entries) + "\n"
            )

        # FORM + GUIDE + REF → only when user selected research_reference section
        _agg_section = ""
        if _link_entries and _ref_section_requested:
            if _form_entries:
                _agg_section += f"\n📄 FORM_LINKS{_instruction} — แสดงทั้งหมด:\n" + "\n".join(_fmt_link(d, u) for d, u in _form_entries) + "\n"
            if _guide_entries:
                _agg_section += (
                    f"\n📖 GUIDE_LINKS{_instruction} — เลือกแค่ 1 ลิงก์สำคัญที่สุดเท่านั้น ห้ามเกิน 1 ลิงก์:\n"
                    + "\n".join(_fmt_link(d, u) for d, u in _guide_entries) + "\n"
                )
            if _ref_entries and _user_asked_reference:
                _agg_section += f"\n🔗 REFERENCE_LINKS{_instruction} — แสดงเฉพาะเมื่อ user ถาม:\n" + "\n".join(_fmt_link(d, u) for d, u in _ref_entries) + "\n"

        return f"""USER_QUESTION:
{user_question}

SLOTS:
{json.dumps(slots, ensure_ascii=False)}

SELECTED_SECTIONS:
{json.dumps(selected, ensure_ascii=False)}
{_service_section}{_agg_section}
FORMATTING RULES:
- operation_steps in source data may have "Step 1 ...", "Step 2 ..." prefixes from the database.
  When writing the ขั้นตอน section, STRIP the "Step X" prefix completely and present as plain numbered list: "1. ...", "2. ..." etc.
  NEVER output "1) Step 1 ..." or "• Step 1 ..." — the word "Step" must not appear in the output.

DOCUMENTS ({len(state.current_docs or [])} found):
{json.dumps(docs_json, ensure_ascii=False)}

Return JSON:
""".strip()

    _URL_TRAILING_RE = re.compile(r'https?://\S+$')
    _URL_CONTINUATION_RE = re.compile(r'^[a-zA-Z0-9._/\-?=&%+#@!~,;:]+')

    def _fix_line_wrapping(self, text: str) -> str:
        """Fix URL lines that LLM wrapped mid-path.
        Case 1: lone '- ' or '• ' bullet before a URL on the next line → join.
        Case 2: URL split mid-path across two lines → join.
        Does NOT touch Thai text — too risky to auto-join Thai sentences.
        """
        if not text:
            return text
        # Case 0: convert indented numbered sub-items to bullets
        # e.g. "   1. ระวางโทษ..." → "   • ระวางโทษ..."
        text = re.sub(r'(?m)^([ \t]{2,})\d+[).]\s+', r'\1• ', text)

        # Case 3: section header and first numbered item on the same line
        # e.g. "📋 ขั้นตอนการดำเนินการ 1. เข้าสู่ระบบ" → split before "1."
        text = re.sub(
            r'([\u2600-\u27BF\U0001F300-\U0001FFFF][^\n]*?[ก-๙])\s+(\d+[).]\s)',
            r'\1\n\2',
            text,
        )

        lines = text.split("\n")
        result = []
        i = 0
        while i < len(lines):
            line = lines[i]
            if i + 1 < len(lines):
                next_line = lines[i + 1]
                stripped_next = next_line.strip()
                # Case 1: lone bullet/dash with URL on next line e.g. "   - \nhttps://..."
                if re.match(r'^[\-•]\s*$', line.strip()) and stripped_next.startswith("http"):
                    result.append(line.rstrip() + " " + stripped_next)
                    i += 2
                    continue
                # Case 2: URL split mid-path — line ends with URL chars, next continues URL
                if (self._URL_TRAILING_RE.search(line) and
                        stripped_next and
                        self._URL_CONTINUATION_RE.match(stripped_next) and
                        not re.match(r'^[\u0E00-\u0E7F\s\-•*\d]', stripped_next)):
                    result.append(line.rstrip() + stripped_next)
                    i += 2
                    continue
            result.append(line)
            i += 1
        return "\n".join(result)

    def _finalize_answer(self, state: ConversationState) -> str:
        # P0: Always use academic_question (never use slot reply)
        ctx = state.context or {}
        uq = (ctx.get("academic_question") or "").strip()

        if not uq:
            if hasattr(state, "get_last_retrieval_query"):
                uq = (state.get_last_retrieval_query() or "").strip()
            else:
                uq = (state.last_retrieval_query or "").strip()

        uq = uq or getattr(conf, "DEFAULT_RETRIEVAL_FALLBACK_QUERY",
                           "กฎหมายร้านอาหาร ใบอนุญาต ภาษี VAT จดทะเบียน สุขาภิบาล ประกันสังคม")

        prompt = self._build_final_prompt(state, user_question=uq)
        decision = self._call_llm_json(prompt, state=state)

        _ex_raw = decision.get("execution") or {}
        if isinstance(_ex_raw, str):
            try:
                _ex_raw = json.loads(_ex_raw)
            except Exception:
                _ex_raw = {}
        ex = _ex_raw if isinstance(_ex_raw, dict) else {}
        ans = (ex.get("answer") or "").strip()
        if not ans:
            ans = "ขอโทษครับ ตอนนี้ยังไม่พบข้อมูลที่ยืนยันได้ในเอกสาร"
        ans = self._fix_line_wrapping(ans)

        cu = ex.get("context_update", {})
        if isinstance(cu, dict) and cu:
            state.context.update(cu)

        self._mark_done(state)

        # clean transient
        state.context["pending_options"] = {}
        state.context["pending_question"] = ""
        state.context.pop("resolved_selection", None)

        return ans

    # ENTRYPOINT
    def handle(
        self,
        state: ConversationState,
        user_input: str,
        force_intake: bool = False,
        _internal: bool = False,
    ) -> Tuple[ConversationState, str]:
        state.context = state.context or {}
        state.persona_id = self.persona_id

        # DEDUPE: supervisor already appends user; but allow standalone usage too
        if not _internal:
            self._append_user_once(state, user_input)

        user_text = (user_input or "").strip()

        flow = self._get_flow(state)
        stage = (flow.get("stage") if isinstance(flow, dict) else "") or ""

        # Start intake (NO implicit idle stage)
        if not stage:
            # If force-routed here but got greeting/noise/blank -> ask for question (no flow created)
            if force_intake and self._looks_like_greeting_or_noise(user_text):
                msg = "อยากให้ช่วยเรื่องไหนเกี่ยวกับกฎหมาย/ขั้นตอนของร้านอาหารครับ"
                self._append_assistant(state, msg)
                return state, msg

            # If there's a real question -> start intake + retrieve once
            if user_text:
                self._start_intake_with_retrieval(state, user_question=user_text)

                # C2: Pre-populate academic_slots from cross-persona slot memory (no re-asking)
                if hasattr(state, "get_collected_slots"):
                    known_slots = state.get_collected_slots()
                    if known_slots:
                        ctx = state.context or {}
                        existing = ctx.get("academic_slots") or {}
                        if not isinstance(existing, dict):
                            existing = {}
                        for k, v in known_slots.items():
                            if k not in existing:
                                existing[k] = v
                        ctx["academic_slots"] = existing
                        state.context = ctx

                self._ensure_flow(state, stage="awaiting_slots")
                q = self._ask_required_slots(state)

                if not q:  # All slots already known or question specific — skip to sections
                    q2 = self._ask_sections(state)
                    if not q2.strip():  # No sections found — finalize immediately
                        ans = self._finalize_answer(state)
                        self._append_assistant(state, ans)
                        state.round = 0
                        return state, ans
                    self._append_assistant(state, q2)
                    state.round = int(getattr(state, "round", 0) or 0) + 1
                    return state, q2

                self._append_assistant(state, q)
                state.round = int(getattr(state, "round", 0) or 0) + 1
                return state, q

            msg = "อยากให้ช่วยเรื่องไหนเกี่ยวกับกฎหมาย/ขั้นตอนของร้านอาหารครับ"
            self._append_assistant(state, msg)
            return state, msg

        # Refresh stage
        flow = self._get_flow(state) or {}
        stage = (flow.get("stage") or "").strip()
    
        # Stage: awaiting_slots
        if stage == "awaiting_slots":
            # Noise/greeting/empty input while waiting for slots — re-ask (or proceed if all slots known)
            if not user_text or self._looks_like_greeting_or_noise(user_text):
                q = self._ask_required_slots(state)
                if q.strip():
                    self._append_assistant(state, q)
                    return state, q
                # All slots already known — fall through to sections below

            # Otherwise treat as slot answer — save then re-retrieve with slot filters
            self._save_slots_best_effort(state, user_text)
            self._re_retrieve_with_slots(state)

            q2 = self._ask_sections(state)

            # P0: If no sections -> finalize immediately
            if not q2.strip():
                ans = self._finalize_answer(state)
                self._append_assistant(state, ans)
                state.round = 0
                return state, ans

            self._append_assistant(state, q2)
            state.round = int(getattr(state, "round", 0) or 0) + 1
            return state, q2

        # Stage: awaiting_sections -> final answer
        if stage == "awaiting_sections":
            bind = self._bind_choice_if_any(state, user_text)

            # If user sends noise here, re-ask section menu (keep stage)
            if not user_text or (not bind.get("bound") and self._looks_like_greeting_or_noise(user_text)):
                msg = (state.context or {}).get("pending_question") or self._ask_sections(state)
                msg = msg.strip() or "พิมพ์เลขข้อที่ต้องการ (เช่น 1, 2) หรือพิมพ์เลขข้อสุดท้ายเพื่อดูทั้งหมดครับ"
                self._append_assistant(state, msg)
                return state, msg

            self._save_selected_sections(state, user_text, bind)

            ans = self._finalize_answer(state)
            self._append_assistant(state, ans)
            state.round = 0
            return state, ans

        # Stage done or unknown: safe fallback
        fallback = "ขอโทษครับ ผมยังไม่เข้าใจ รบกวนอธิบายเพิ่มอีกนิดได้ไหมครับ"
        self._append_assistant(state, fallback)
        return state, fallback